version: '3.8'
x-db-variables: &db-variables
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_PORT: ${DATABASE_PORT}
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_NAME: ${DATABASE_NAME}

x-be-variables: &be-variables
  BE_API_PORT: ${BE_API_PORT}
  BE_API_HOST: ${BE_API_HOST} 

x-jwt-variables: &jwt-variables
  JWT_SECRET: ${JWT_SECRET}

x-fe-variables: &fe-variables
  FE_PORT: ${FE_PORT}

services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
       - ./postgres_data:/var/lib/postgresql/data/
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DATABASE_NAME}"]
      interval: 60s
      timeout: 60s
      retries: 5
      start_period: 80s

  dev-db-seed:
    build:
      context: ./initiatives-api-server
      dockerfile: Dockerfile.dev.seed
    volumes:
      - ./initiatives-api-server:/app
    environment:
        <<: *db-variables
    depends_on:
      - dev-db
    networks:
      - dev-network

  initiatives-dev-api:
    build:
      context: ./initiatives-api-server
      dockerfile: Dockerfile.dev
    volumes:
      - ./initiatives-api-server:/app
      - ./initiatives-api-server/node_modules/.prisma:/app/node_modules/.prisma # This is to avoid prisma from being generated in ignored modules
      - ignore-be-node_modules:/app/node_modules/
    ports:
      - ${BE_API_PORT}:3333
      - 5555:5555
    environment:
        <<: [*db-variables, *jwt-variables, *be-variables]
        NODE_ENV: development
    depends_on:
      - dev-db
      - dev-db-seed
    networks:
      - dev-network

  initiatives-api-test-watch:
    build:
      context: ./initiatives-api-server
      dockerfile: Dockerfile.dev.tests
    volumes:
      - ./initiatives-api-server:/app
      - ignore-api-test-node_modules:/app/node_modules/
    environment:
        <<: [*db-variables, *jwt-variables, *be-variables]
        NODE_ENV: development
    depends_on:
      - initiatives-dev-api
    networks:
      - dev-network
    restart: "always"
  
  initiatives-dev-client:
    build:
      context: ./initiatives-fe-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./initiatives-fe-app:/app
      - ignore-fe-node_modules:/app/node_modules/
    ports:
      - ${FE_PORT}:${FE_PORT}
    depends_on:
      - initiatives-dev-api
    environment:
        <<: [*be-variables, *fe-variables]
        NODE_ENV: development


volumes:
  ignore-be-node_modules:
  ignore-fe-node_modules:
  ignore-api-test-node_modules:
networks:
  dev-network:
