FROM node:20-slim

WORKDIR /app

RUN apt-get update && apt-get install -y ca-certificates openssl

COPY ./ ./
RUN yarn global add @nestjs/cli
RUN yarn install --frozen-lockfile

CMD yarn start:dev --preserveWatchOutput
