FROM node:18-slim
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates openssl
COPY package.json ./
COPY yarn.lock ./
COPY prisma ./
RUN yarn install
CMD yarn prisma generate && yarn prisma:dev:deploy && yarn db:dev:seed